import { describe, it, expect } from 'vitest'
import { summaryLines } from '../../mcp/tools/summary-text'
import { matchedResourceLines } from '../../mcp/tools/datasets'

/**
 * The gates here are the resource page's, and the point of the tests is that
 * they stay the page's: the same row read two ways that disagree about what is
 * public is exactly what ADR-053 §4.1 puts in the projection to prevent, and
 * the projection cannot reach these — the switch is an environment variable and
 * `hidden` travels in the meta rather than being scrubbed out of it.
 */
describe('summaryLines', () => {
  const written = { source: 'ai' as const, version: 1, material: 'schema' as const }

  it('carries the abstract, its extent, and the version it describes', () => {
    const lines = summaryLines(
      'a description',
      { ...written, coverage: { read: 100, total: 1200 } },
      1,
      true
    )

    expect(lines.join('\n')).toContain('the column layout and the first 100 of 1200 rows')
    expect(lines.join('\n')).toContain('describes v1')
    expect(lines.join('\n')).toContain('Generated by AI')
  })

  it('says the file has moved past the version described', () => {
    const lines = summaryLines('a description', written, 4, true)

    expect(lines.join('\n')).toContain('describes v1, and the file is now v4')
  })

  it('says nothing at all about an abstract an editor hid', () => {
    // The reason a *previous* run recorded is still on the row. Offering it in
    // place of text someone took down answers a question nobody asked — and
    // reads as though the abstract was never written.
    expect(summaryLines(null, { hidden: true, skipReason: 'too-large' }, 1, true)).toEqual([])
    expect(summaryLines('still here', { ...written, hidden: true }, 1, true)).toEqual([])
  })

  it("leaves a person's own text without a generated one's provenance", () => {
    // Editing an abstract sets the source and leaves the rest of the meta
    // alone, so the material and version still describe the sentence that was
    // replaced. Labelling a person's writing with them is false twice over.
    const lines = summaryLines(
      'what the publisher wrote',
      { source: 'human', version: 1, material: 'schema', coverage: { read: 100, total: 1200 } },
      4,
      true
    )

    expect(lines).toEqual(['Description: what the publisher wrote'])
  })

  it('withholds the reason on a site that writes no abstracts', () => {
    // The reasons outlive the setting, because they are on the row: a
    // deployment that tried abstracts and then cleared AI_SUMMARY_MODEL keeps
    // every one it recorded. A reason explains a feature this site lacks.
    expect(summaryLines(null, { skipReason: 'too-large' }, 1, false)).toEqual([])
    expect(summaryLines(null, { skipReason: 'too-large' }, 1, undefined)).toEqual([])
  })

  it('gives the reason where the site does write them', () => {
    const lines = summaryLines(null, { skipReason: 'format-mismatch' }, 1, true)

    expect(lines.join('\n')).toContain('the source link may be dead')
  })

  it("keeps to itself the reasons that are not a reader's business", () => {
    expect(summaryLines(null, { skipReason: 'not-public' }, 1, true)).toEqual([])
    expect(summaryLines(null, { skipReason: 'hidden' }, 1, true)).toEqual([])
  })

  it('says nothing where there is nothing to say', () => {
    expect(summaryLines(null, null, 1, true)).toEqual([])
    expect(summaryLines(undefined, undefined, undefined, true)).toEqual([])
  })
})

describe('matchedResourceLines', () => {
  const res = (i: number) => ({ id: `r${i}`, name: `f${i}.csv`, format: 'CSV' })

  it('names the files and what each match is on account of', () => {
    const text = matchedResourceLines({
      matchedResources: [
        { ...res(1), matchSource: 'metadata' },
        { ...res(2), matchSource: 'content' },
        { ...res(3), matchSource: 'semantic', similarity: 0.42 },
        { ...res(4), matchSource: 'metadata', matchedOn: ['summary'] },
      ],
    }).join('\n')

    expect(text).toContain('f1.csv [CSV] (in its name or description')
    expect(text).toContain('in its contents')
    expect(text).toContain('by meaning 0.42')
    expect(text).toContain('in its AI-written description')
  })

  it('counts the remainder from the total, not from what was carried', () => {
    // The adapters carry at most MAX_MATCHED_RESOURCES_PER_PACKAGE and keep the
    // real total beside them. Subtracting from the array under-reports every
    // package that matched past the cap.
    const text = matchedResourceLines({
      matchedResources: Array.from({ length: 100 }, (_, i) => res(i)),
      matchedResourcesCount: { total: 150, atLeast: false },
    }).join('\n')

    expect(text).toContain('…and 145 more')
  })

  it('says a floor is a floor', () => {
    const text = matchedResourceLines({
      matchedResources: Array.from({ length: 100 }, (_, i) => res(i)),
      matchedResourcesCount: { total: 150, atLeast: true },
    }).join('\n')

    expect(text).toContain('…and at least 145 more')
  })

  it('keeps a floor visible when it sits below what was carried', () => {
    // A semantic hit joining a capped list leaves the total where it was and
    // marks it a floor rather than raising it on a guess, so the count can be
    // smaller than the array. Saying nothing then offers the named ones as the
    // whole of it — the one reading the floor exists to prevent.
    const text = matchedResourceLines({
      matchedResources: [res(1), res(2)],
      matchedResourcesCount: { total: 1, atLeast: true },
    }).join('\n')

    expect(text).toContain('…and possibly more')
  })

  it('says nothing more where the count is exact and all of it is named', () => {
    const text = matchedResourceLines({
      matchedResources: [res(1), res(2)],
      matchedResourcesCount: { total: 2, atLeast: false },
    }).join('\n')

    expect(text).not.toContain('…and')
  })

  it('falls back to the array where no count came with it', () => {
    const text = matchedResourceLines({
      matchedResources: Array.from({ length: 8 }, (_, i) => res(i)),
    }).join('\n')

    expect(text).toContain('…and 3 more')
  })

  it('says nothing for a dataset nothing matched inside', () => {
    expect(matchedResourceLines({})).toEqual([])
    expect(matchedResourceLines({ matchedResources: [] })).toEqual([])
  })
})
