import { describe, it, expect, vi, beforeEach } from 'vitest'
import { render, screen } from '@testing-library/react'
import { ResourceAbstract } from '../resource-abstract'

/** Whether this deployment writes abstracts at all — the reasons depend on it */
const summaryEnabled = vi.fn<() => boolean | null>(() => true)
vi.mock('@/hooks/use-site-settings', () => ({
  useSiteSettings: () => ({ resourceSummaryEnabled: summaryEnabled() }),
}))

beforeEach(() => {
  summaryEnabled.mockReturnValue(true)
})

describe('ResourceAbstract (ADR-053)', () => {
  it('says how much of the file was read, in the reader\u2019s terms', () => {
    render(
      <ResourceAbstract
        summary="この資料は交通事故の統計である。"
        summaryMeta={{
          source: 'ai',
          material: 'schema',
          coverage: { read: 5, total: 163 },
          version: 3,
          generatedAt: '2026-09-13T00:00:00Z',
        }}
      />
    )

    expect(screen.getByRole('heading', { name: /AI/ })).toBeInTheDocument()
    expect(screen.getByText('この資料は交通事故の統計である。')).toBeInTheDocument()
    // "All of it" and "the first five of 163 rows" are different claims, and
    // the abstract itself is forbidden to mention the material it was given
    const notice = screen.getByText(/first 5 of 163 rows/)
    // The same spelling the version history uses, so the two can be compared
    expect(notice).toHaveTextContent('v3')
    expect(notice).toHaveTextContent('2026')
    expect(screen.getByText(/authoritative record/)).toBeInTheDocument()
  })

  it('says so when the file has moved on since the abstract was written', () => {
    // Left to be worked out, this is the state nobody goes looking for: the
    // reader would have to find the history, read the number and compare
    render(
      <ResourceAbstract
        summary="…"
        summaryMeta={{ source: 'ai', material: 'schema', version: 4 }}
        latestVersion={7}
      />
    )

    expect(screen.getByText(/now at v7/)).toBeInTheDocument()
  })

  it('says nothing of the kind while the abstract still describes the live file', () => {
    render(
      <ResourceAbstract
        summary="…"
        summaryMeta={{ source: 'ai', material: 'schema', version: 4 }}
        latestVersion={4}
      />
    )

    expect(screen.queryByText(/now at v/)).not.toBeInTheDocument()
  })

  it('says the whole file was read where the original was sent', () => {
    render(
      <ResourceAbstract
        summary="…"
        summaryMeta={{ source: 'ai', material: 'original', version: 1 }}
      />
    )

    expect(screen.getByText(/Read the whole file/)).toBeInTheDocument()
  })

  it('falls back to no quantity for an abstract written before the extent was recorded', () => {
    render(<ResourceAbstract summary="…" summaryMeta={{ source: 'ai', material: 'schema' }} />)

    expect(screen.getByText(/Read part of the file/)).toBeInTheDocument()
  })
  it('does not disclaim a person\u2019s own text', () => {
    render(<ResourceAbstract summary="人が書いた説明。" summaryMeta={{ source: 'human' }} />)

    expect(screen.queryByText(/authoritative record/)).not.toBeInTheDocument()
  })

  it("leaves a person's own text unlabelled", () => {
    render(<ResourceAbstract summary="人が書いた説明。" summaryMeta={{ source: 'human' }} />)

    expect(screen.getByText('人が書いた説明。')).toBeInTheDocument()
    expect(screen.queryByText(/generated by AI/)).not.toBeInTheDocument()
    expect(screen.queryByRole('heading')).not.toBeInTheDocument()
  })

  it('says which part of a long document was read', () => {
    // A PDF past the page limit goes as its first pages rather than not at all
    // (ADR-053 §3.6), and that is the one original a reader must not take for
    // the whole file.
    render(
      <ResourceAbstract
        summary="この報告書は年次統計をまとめたものである。"
        summaryMeta={{
          source: 'ai',
          material: 'original',
          coverage: { read: 50, total: 320 },
          version: 1,
          generatedAt: '2026-09-15T00:00:00Z',
        }}
      />
    )

    expect(screen.getByText(/first 50 pages of 320/)).toBeInTheDocument()
  })

  it('claims nothing about pages for an original that went whole', () => {
    render(
      <ResourceAbstract
        summary="この画像は道路標識を写したものである。"
        summaryMeta={{ source: 'ai', material: 'original', version: 1 }}
      />
    )

    expect(screen.getByText(/Read the whole file|whole file/)).toBeInTheDocument()
  })

  it('gives the reason when nothing was written', () => {
    render(<ResourceAbstract summary={null} summaryMeta={{ skipReason: 'too-large' }} />)

    expect(screen.getByText(/exceeds the size limit/)).toBeInTheDocument()
  })

  it('gives no reason on a site that does not write abstracts', () => {
    // The reason explains a feature. Where the feature is off, it tells a
    // reader that something they cannot have was not done for them — and the
    // reasons outlive the setting, because they are on the row.
    summaryEnabled.mockReturnValue(false)

    const { container } = render(
      <ResourceAbstract summary={null} summaryMeta={{ skipReason: 'too-large' }} />
    )

    expect(container).toBeEmptyDOMElement()
  })

  it('waits for the answer rather than guessing it', () => {
    summaryEnabled.mockReturnValue(null)

    const { container } = render(
      <ResourceAbstract summary={null} summaryMeta={{ skipReason: 'too-large' }} />
    )

    expect(container).toBeEmptyDOMElement()
  })

  it('says nothing at all about one an editor took down', () => {
    const { container } = render(
      <ResourceAbstract summary={null} summaryMeta={{ skipReason: 'hidden' }} />
    )

    expect(container).toBeEmptyDOMElement()
  })

  it('does not answer with an older reason once an editor has hidden it', () => {
    // A file that outgrew the limit keeps the abstract it had, with the reason
    // beside it. Hiding the abstract must not leave the reason standing in its
    // place — that answers a question the reader never asked.
    const { container } = render(
      <ResourceAbstract summary={null} summaryMeta={{ hidden: true, skipReason: 'too-large' }} />
    )

    expect(container).toBeEmptyDOMElement()
  })

  it('says nothing where the catalog simply has no abstract for this file', () => {
    const { container } = render(<ResourceAbstract summary={null} summaryMeta={{}} />)

    expect(container).toBeEmptyDOMElement()
  })
})
