import type { ResourceSummaryMeta } from '@kukan/shared'

/**
 * How much of the file the abstract was written from, in a clause.
 *
 * An agent that reads "sales fell in the third quarter" off an abstract has no
 * way to know whether the model saw the whole table or its first hundred rows,
 * and the model is forbidden from saying so itself (ADR-053 §7). Without the
 * extent, the two are the same sentence — and only one of them supports the
 * conclusion an agent would draw from it.
 */
function extent(meta: ResourceSummaryMeta): string | null {
  const { material, coverage } = meta
  if (!material) return null
  if (material === 'image') return 'the whole image'
  if (material === 'original') {
    return coverage?.total
      ? `the first ${coverage.read} of ${coverage.total} pages`
      : 'the whole file'
  }
  if (!coverage?.read) return null
  if (material === 'schema') {
    return coverage.total
      ? `the column layout and the first ${coverage.read} of ${coverage.total} rows`
      : `the column layout and the first ${coverage.read} rows`
  }
  if (material === 'files') {
    return coverage.total
      ? `${coverage.read} of the ${coverage.total} file names inside`
      : `${coverage.read} of the file names inside`
  }
  // 'text' and 'text-head': characters off the front
  return `about the first ${coverage.read} characters`
}

/** Why no abstract exists, in the terms a caller can act on. */
const SKIPPED: Record<string, string> = {
  'too-large': 'the file is over the size limit',
  rejected: 'the file was more than the model could read at once',
  'unsupported-format': 'the model cannot read this format',
  'format-mismatch':
    'the bytes are not the format this resource declares — the source link may be dead',
  'no-material': 'the pipeline found nothing to describe',
  'provider-unavailable': 'this site has no model configured',
  disabled: 'this site does not generate them',
  'not-public': 'the resource is not public',
  hidden: 'an editor hid it',
}

/**
 * The abstract as an agent should read it: the sentences, what they were
 * written from, and which version they describe.
 *
 * The gates are the resource page's, and they have to be — the same row read
 * two ways that disagree about whether text is public is the bug the page's
 * projection exists to prevent (ADR-053 §4.1). An editor who hid the abstract
 * hid the block, a reason explains a feature the site may not have, and text a
 * person wrote is not a generated sentence and carries no notice.
 *
 * Returned as lines rather than a blob so a caller can place it; empty when
 * there is nothing to say at all, which is the ordinary case on a site that
 * has abstracts switched off.
 *
 * `latestVersion` earns its place by answering the question the text cannot: a
 * description of v2 served beside a v5 file is not wrong, it is stale, and an
 * agent that cannot tell has no reason to doubt it.
 */
export function summaryLines(
  summary: string | null | undefined,
  meta: ResourceSummaryMeta | null | undefined,
  latestVersion?: number | null,
  /** Whether this deployment writes abstracts at all — the reasons outlive the
   *  setting, because they are on the row rather than in the environment */
  enabled?: boolean
): string[] {
  // An editor who took the abstract down took the whole block with it. The
  // reason a previous run gave is still on the row, and offering that in place
  // of what was hidden answers a question nobody asked.
  if (meta?.hidden) return []

  if (!summary) {
    if (enabled !== true) return []
    const reason = meta?.skipReason
    // 'hidden' is handled above; a draft's absence is not the reader's business
    if (!reason || reason === 'hidden' || reason === 'not-public') return []
    const said = SKIPPED[reason]
    return said ? [`No AI-written description: ${said}.`] : []
  }

  // A person's own text, carrying none of the provenance of the generated one
  // it replaced: the material and version still on the row describe a sentence
  // nobody is reading any more.
  if (meta?.source === 'human') return [`Description: ${summary}`]

  const written = ['AI-written description']
  const from = meta && extent(meta)
  if (from) written.push(`read ${from}`)
  if (meta?.version) {
    written.push(
      latestVersion && latestVersion > meta.version
        ? `describes v${meta.version}, and the file is now v${latestVersion}`
        : `describes v${meta.version}`
    )
  }
  return [
    `${written.join('; ')}:`,
    summary,
    '(Generated by AI. Check the file itself before relying on this.)',
  ]
}
